In [15]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import mglearn
from IPython.display import display

In [108]:
from ucimlrepo import fetch_ucirepo 
# fetch dataset 
wine_quality = fetch_ucirepo(id=186) 
# data (as pandas dataframes) 
X = wine_quality.data.features 
y = wine_quality.data.targets['quality']

In [135]:
print(wine_quality.data)

{'ids': None, 'features':       fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
0               7.4              0.70         0.00             1.9      0.076   
1               7.8              0.88         0.00             2.6      0.098   
2               7.8              0.76         0.04             2.3      0.092   
3              11.2              0.28         0.56             1.9      0.075   
4               7.4              0.70         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
6492            6.2              0.21         0.29             1.6      0.039   
6493            6.6              0.32         0.36             8.0      0.047   
6494            6.5              0.24         0.19             1.2      0.041   
6495            5.5              0.29         0.30             1.1      0.022   
6496            6.0              0.21         0.38             0.8      0.020   

 

In [109]:
print("############ Assignment 1 Question 1 BEGIN ############")
print(wine_quality.data.original['color'].value_counts())
print("############ Assignment 1 Question 1 END ############")

############ Assignment 1 Question 1 BEGIN ############
color
white    4898
red      1599
Name: count, dtype: int64
############ Assignment 1 Question 1 END ############


In [110]:
print("############ Assignment 1 Question 2 BEGIN ############")
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, train_size=0.75, random_state=0)
from sklearn.neighbors import KNeighborsClassifier

print("############ Assignment 1 Question 2a BEGIN ############")
clf = KNeighborsClassifier(n_neighbors=1)
clf.fit(X_train, y_train)
print("Test set predictions:", clf.predict(X_test))
print("Test set accuracy: {:.2f}".format(clf.score(X_test, y_test)))

############ Assignment 1 Question 2 BEGIN ############
############ Assignment 1 Question 2a BEGIN ############
Test set predictions: [6 6 6 ... 5 6 5]
Test set accuracy: 0.58


In [111]:
print("############ Assignment 1 Question 2b BEGIN ############")
clf = KNeighborsClassifier(n_neighbors=3)
clf.fit(X_train, y_train)
print("Test set predictions:", clf.predict(X_test))
print("Test set accuracy: {:.2f}".format(clf.score(X_test, y_test)))

############ Assignment 1 Question 2b BEGIN ############
Test set predictions: [6 6 6 ... 5 6 6]
Test set accuracy: 0.48


In [112]:
print("############ Assignment 1 Question 2c BEGIN ############")
clf = KNeighborsClassifier(n_neighbors=5)
clf.fit(X_train, y_train)
print("Test set predictions:", clf.predict(X_test))
print("Test set accuracy: {:.2f}".format(clf.score(X_test, y_test)))
print("############ Assignment 1 Question 2 END ############")

############ Assignment 1 Question 2c BEGIN ############
Test set predictions: [6 6 6 ... 6 6 6]
Test set accuracy: 0.48
############ Assignment 1 Question 2 END ############


In [113]:
print("############ Assignment 1 Question 3 BEGIN ############")
from sklearn.neighbors import KNeighborsRegressor
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, train_size=0.75, random_state=0)

############ Assignment 1 Question 3 BEGIN ############


In [114]:
print("############ Assignment 1 Question 3a BEGIN ############")
reg = KNeighborsRegressor(n_neighbors=1)
reg.fit(X_train, y_train)
print("Test set predictions:\n", reg.predict(X_test))
print("Test set R^2: {:.2f}".format(reg.score(X_test, y_test)))

############ Assignment 1 Question 3a BEGIN ############
Test set predictions:
 [6. 6. 6. ... 5. 6. 5.]
Test set R^2: -0.02


In [115]:
print("############ Assignment 1 Question 3b BEGIN ############")
reg = KNeighborsRegressor(n_neighbors=3)
reg.fit(X_train, y_train)
print("Test set predictions:\n", reg.predict(X_test))
print("Test set R^2: {:.2f}".format(reg.score(X_test, y_test)))

############ Assignment 1 Question 3b BEGIN ############
Test set predictions:
 [5.66666667 6.         6.         ... 5.33333333 6.         5.66666667]
Test set R^2: 0.10


In [116]:
print("############ Assignment 1 Question 3c BEGIN ############")
reg = KNeighborsRegressor(n_neighbors=5)
reg.fit(X_train, y_train)
print("Test set predictions:\n", reg.predict(X_test))
print("Test set R^2: {:.2f}".format(reg.score(X_test, y_test)))

############ Assignment 1 Question 3c BEGIN ############
Test set predictions:
 [5.6 6.4 5.6 ... 5.6 6.  5.6]
Test set R^2: 0.14


In [117]:
print("############ Assignment 1 Question 3d BEGIN ############")
print("At 5 neighbors, the R-square hit its highest level.")
print("############ Assignment 1 Question 3 END ############")

############ Assignment 1 Question 3d BEGIN ############
At 5 neighbors, the R-square hit its highest level.
############ Assignment 1 Question 3 END ############


In [118]:
print("############ Assignment 1 Question 4 BEGIN ############")
# TBD
print("############ Assignment 1 Question 4 END ############")

############ Assignment 1 Question 4 BEGIN ############
############ Assignment 1 Question 4 END ############


In [119]:
print("############ Assignment 1 Question 5 BEGIN ############")
print("KNN Classifier treats Wine Quality like a nominal variable.")
print("The KNN Regressor treats Wine Quality like ordinal variable.") 
print("KNN Regressor is better suited than KNN Classifier, because there is a clear, meaningful ranking. Higher wine qualities are better than lower values.")
print("KNN Classifier would treat each level of wine quality the same and as having no intrinsic order.")
print("############ Assignment 1 Question 5 END ############")

############ Assignment 1 Question 5 BEGIN ############
KNN Classifier treats Wine Quality like a nominal variable.
The KNN Regressor treats Wine Quality like ordinal variable.
KNN Regressor is better suited than KNN Classifier, because there is a clear, meaningful ranking. Higher wine qualities are better than lower values.
KNN Classifier would treat each level of wine quality the same and as having no intrinsic order.
############ Assignment 1 Question 5 END ############


In [120]:
print("############ Assignment 1 Question 6 BEGIN ############")
# Visualization here (TBD)
print(wine_quality.data.targets['quality'].value_counts())
print("There is a class imbalance; there's vastly different amounts of data points for each class (wine quality), ranging from 5 wines to 2836 wines.")
print("############ Assignment 1 Question 6 END ############")

############ Assignment 1 Question 6 BEGIN ############
quality
6    2836
5    2138
7    1079
4     216
8     193
3      30
9       5
Name: count, dtype: int64
There is a class imbalance; there's vastly different amounts of data points for each class (wine quality), ranging from .
############ Assignment 1 Question 6 END ############


In [137]:
print("############ Assignment 1 Question 7 BEGIN ############")
print("The fact that feature scaling was not allowed does impact the results of the KNN classifier, because the features of the dataset have vastly different magnitudes (ex: density is between 0-1, total sulfur dioxide can range between 0-200).")
print("############ Assignment 1 Question 7 END ############")

############ Assignment 1 Question 7 BEGIN ############
The fact that feature scaling was not allowed does impact the results of the KNN classifier, because the features of the dataset have vastly different magnitudes (ex: density is between 0-1, total sulfur dioxide can range between 0-200).
############ Assignment 1 Question 7 END ############
